### ISSUE TITLE
cannot open file 'Data/LINCS.csv': No such file or directory

### ISSUE THREAD

**Issue by HinamonAmu** [WINGHARE/RNCE#1]
Hello, when I was running the r script: **main-ctrpv-lincs.R**, I encountered the following error "cannot open file' **DATA/lincs.csv**': no such file or directory", but I didn't see this file in the Data folder. How can I solve this problem? Thank you.

**Comment by juychen** [comment]
> Hello, when I was running the r script: **main-ctrpv-lincs.R**, I encountered the following error "cannot open file' **DATA/lincs.csv**': no such file or directory", but I didn't see this file in the Data folder. How can I solve this problem? Thank you.

Updated
